### ISSUE TITLE
League Creation Start Date Still Following UTC Timezone

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#123]
**Description**
If a user tries to create a league that starts the next day, they might not be able to depending on the UTC timezone. I.e. users can't create a league that starts the next day after about 4:00 PM PST, but they can still join a league that starts the next day.

**Steps to Reproduce**
1. Go to the Create League page after about 4:00 PM PST, which is around the start of the next day for UTC timezone
2. Set the start date to tomorrow
3. Press Create League and nothing will happen

**Expected Behavior**
Leagues should be allowed to be created if they start the next day, similar to how users are now able to join leagues that start the next day, without any problems and to maintain consistency.

**Actual Behavior**
Leagues that start the next day cannot be created after about 4:00 PM PST, which is about the start of the next day in UTC timezone.

**Comment by lvcodes3** [comment]
I believe this occurs in the frontend portion of the create a league page because the backend only receives the data already sent by the frontend. It's also a bit strange considering that when creating a league, the start and end date of the league does not care about the time when the league starts or ends, which is fine, just a bit confusing to why it is doing this.
